### ISSUE TITLE
Allow manual control of how much is batched to each worker

### ISSUE THREAD

**Issue by CapedBojji** [blorbee1/ComputeLua#1]
Currently the batch size is set manually to 50,  this means even when i dont need the actor to run that many times it does

**Comment by CapedBojji** [comment]
![image](https://github.com/blorbee1/ComputeLua/assets/115787932/6f58f927-46e5-4ef6-92d0-8f8571649748)
![image](https://github.com/blorbee1/ComputeLua/assets/115787932/d4f7e1d3-f1d0-4c1d-88cd-326944f6d6bb)
this is the potential fix

**Comment by blorbee1** [comment]
Your method of fixing it would cause the dispatch ID to be some huge number and not match the indices of the Compute Buffers. But I will add the ability to edit batches and fix that problem you mentioned, 50 will be the default since from testing it is the fastest batch size, anything lower or higher would be slower. The threads hould not even be a small number since it would run at the same speed in serial or parallel if it was a small number
